---
- hosts: all
#  become: true

  tasks:
  - name: building docker image using war file
    command: docker build -t docker-webapp-image:latest .
    args:
      chdir: /opt/docker

  - name: Create tag to image
    command: docker tag docker-webapp-image mbsujai/mbs-nodejs-webapp

  - name: Push image on to dockerhub
    command: docker push deraviyam/docker-webapp-image

  - name: Remove docker images from ansible server
    command: docker rmi docker-webapp-image:latest mbsujai/mbs-nodejs-webapp
    ignore_errors: yes
